MutableCurve: the generic version of FlexSpline.
Freedom-of-Form-Foundation/anatomy3d pull request #60
Opened 2021-08-22 22:21 UTC by AdamNorberg

During today's meeting, we discussed bezier curves as a better approach than our current cubic spline interpolation. Bezier curves are defined by a sequence of (point, angle, magnitude) vectors rather than only a sequence of points, so we need something that is flexible about the type of control point it uses.

MutableCurve makes everything generic: the control point space and the output point space are generic types, and the interpolation algorithm is a parameter. The point generation algorithm is a parameter because C# doesn't have a way to say "this type has a constructor with a specific signature" as a generic constraint; it _does_ have "this type is default constructable", but not arbitrary signatures, so we have a factory type to bolt the dirty callback to mutable point types. Mutable point types are responsible for calling the callback upon  mutation.
 
In C++, we'd be able to write a NewPoint variation that takes whatever parameters the point constructor would like (or that the point factory would like, whichever), using perfect forwarding template patterns. C# doesn't give us that, so we're just going to have to construct all of our points at some default location and they all get assigned piecewise later, which is annoying. One way to be marginally less annoying is for points to have - in addition to their properties to set one field at a time - a .Set method, for assigning all properties at once (with a single dirtying of the collection); then we'd get calls like `MutableBezierPoint p0 = curve.NewPoint().Set(x, y, theta, m);` which seems not-too-bad.

ICurveFactory is responsible for doing any organization or sorting it needs on the incoming collection of points. Its curve would probably rather be built with immutable points anyway, so the curve factory will typically have some conversion to do. MutableCurve abstracts away the I/O for a mutable curve but we still have to write actual algorithms to construct curves. Similarly, the mutable point types are responsible for invoking the callback at appropriate times. We could write a generic type that combines an immutable point (or, for that matter, a value-type point) and a callback and only offers overwriting the entire point at once; this seems clumsy, but it's an option if we decide we want it.

2021-08-29 21:33 UTC, AdamNorberg commented
Unit tests and documentation are written. Please review.

2021-09-12 15:04 UTC, Lathreas requested changes
Alright, here's a review at last! I like the overall structure, and with your new PR showing the possible implementation of it, that factory-based system looks very clean and nice. I don't have a whole lot of comments on code style. There is some general stuff about the file location (which is why I'm putting this on 'request changes'), and other than that a few naming questions. I do think the unit tests might benefit from a few comments here and there indicating what it is intending to test, since it took me a while to read through it without them. Other than that, looking very good! I'll review your newer PR now.

2021-09-14 19:59 UTC, zennithn approved these changes
I've looked through and don't have any specific things to comment on. The code is hard for me to intuit, so I can only give a superficial approval right now.

Here are things I'll recommend, but that I don't want to hold up approval for:
 - I'd love to see a diagram or flow chart of where MutableCurve fits compared to other similar classes, especially in terms of inheritance.
 - I'd also like to see the incorporation of sufficient code (such as other classes, including either users of this class, or specialized subclasses if needed) that lets MutableCurve be used in the application, to test in the 3D viewer, similar to how I was able to diagnose issues in the LongBone underlying geometry. Until that point, my ability to give meaningful feedback will still be a bit limited!

2021-09-19 03:43 UTC, AdamNorberg commented on engine/geometry/MutableCurve.cs
> +        public TOut GetDerivativeAt(Real x, uint derivative) => CurrentCurve().GetDerivativeAt(x, derivative);
Moved.

2021-09-19 03:43 UTC, AdamNorberg commented on engine/geometry/MutableCurve.cs
> +        TOut GetDerivativeAt(Real x, uint derivative);
Done.

2021-09-19 03:43 UTC, AdamNorberg commented on engine/geometry/MutableCurve.cs
> +        /// render very well.</remarks>
Acknow;edged.

2021-09-19 04:06 UTC, AdamNorberg commented on engine/geometry/MutableCurve.cs
> +        }
Some curves may need more than 2 points to be properly defined. It would also require a more complex constructor. Any curve render can be suddenly invalid if the points go somewhere insensible, overlapping, or out-of-range. Etc.

I would rather err on the side of a simpler implementation, especially since "create the thing, then define it" seems like a reasonable workflow. If we discover that we're writing bugs that only show up at runtime, then let's revisit this, I'll write the more restricted constructor and the extra checks then.

2021-09-19 04:39 UTC, AdamNorberg commented on EngineTests/geometry/MutableCurveTests.cs
> +        public void AssertOnCurve(ICurve<Real> curve)
_LiteralResultPoint_ is checking what's on the curve - it's LiteralCurve that is only defined at its exact points.

2021-09-19 04:43 UTC, AdamNorberg commented on engine/geometry/MutableCurve.cs
> +    public class MutableCurve<TControl, TOut>:ICurve<TOut>,IEnumerable<TControl> where TControl:class
Done.

2021-09-19 04:45 UTC, AdamNorberg commented on EngineTests/geometry/MutableCurveTests.cs
> +namespace EngineTests.geometry
Done.

2021-09-19 05:47 UTC, AdamNorberg commented
MutableCurve implements interfaces that describe curve-like behavior, but does not inherit from any other class. Its interface is complicated, because it's using other types to implement the details - it relies on classes that don't exist yet to be points, be moving points, be the curve, and tell this class how to make points and curves.

In future patches, we'll write classes derived from this one, which will be usable inside UI components. This one is too abstract to be directly used, but the pull request I have out for MutableCubicSpline1D shows this class in motion.

2021-09-19 05:47 UTC, AdamNorberg commented
Oh crud, I implemented all my changes for this on the wrong branch, I'll fix it in the morning.

2021-09-19 16:18 UTC, AdamNorberg commented
I think I fixed the branch - I fast-forwarded this one onto the spline branch I accidentally committed last night's changes to, then deleted the actual spline part. Review, please?

2021-10-02 12:20 UTC, Lathreas approved these changes
LGTM! Since they are simple refactorings, I won't repeat the previous review. Can be merged in my opinion!

2021-10-02 12:26 UTC, Lathreas approved these changes

2021-10-02 16:24 UTC, merged