Create LinearSpline1D and test code in ExampleBone
Freedom-of-Form-Foundation/anatomy3d pull request #62
Opened 2021-09-06 17:17 UTC by zennithn

Create LinearSpline1D and test code in ExampleBone. Connected to issue https://github.com/Freedom-of-Form-Foundation/anatomy3d/issues/58.

**SolveRaytrace() method is not yet functional and just returns null.**

2021-09-14 19:37 UTC, zennithn commented
I just realized that I never actually pressed the button to request review. Sorry about that!

2021-10-02 10:14 UTC, Lathreas requested changes
Alright! Sorry for the long wait, here's the review. There mostly some style things to keep the repository clean. I think once these points are addressed it should be ready for merger. Thanks again!

2021-10-02 10:14 UTC, Lathreas commented on engine/calculus/LinearSpline1D.cs
> +			//float t = (x - x1) / dx;
Since these statements are unused, they should be removed.

2021-10-02 10:14 UTC, Lathreas commented on engine/calculus/LinearSpline1D.cs
> +			float global_y = local_y + y1;
Good naming scheme of those variables! Nice and clear, I like it.

2021-10-02 10:14 UTC, Lathreas commented on engine/calculus/LinearSpline1D.cs
> +			float local_y = local_x * (slope);
Just a style thing nitpick of course; but you can remove the parentheses around `slope` to make the code a little cleaner.

2021-10-02 10:14 UTC, Lathreas commented on engine/calculus/LinearSpline1D.cs
> +			}
This seems to be able to be condensed into a single loop. Let me know if that's indeed the case!

```suggestion
			// Recursively find the _parameters:
			for (int i = 0; i < points.Count; i++)
			{
				float dx = Points.Key[i] - Points.Key[i - 1];
				float dy = Points.Value[i] - Points.Value[i - 1];

				_parameters[i] = dy / dx;
			}
```

You simply start at `i=0` instead of `i=1`, so that you get the first iteration for free. If I recall correctly, the reason that this was different in the other splines was because the first segment was a special case and needed to be a line segment instead of a higher-order curve, but since they're all line segments in this case, that doesn't matter anymore of course.

2021-10-02 10:14 UTC, Lathreas commented on engine/calculus/LinearSpline1D.cs
> +		///		\f$x\f$ for which the equation is true. \f$q(x)\f$ is the quadratic spline. The _parameters z0 and c
`quadratic spline` should be `linear spline`

2021-10-02 16:22 UTC, zennithn commented on engine/calculus/LinearSpline1D.cs
> +		}
Good point. Thanks!

2021-10-02 16:27 UTC, zennithn commented on engine/calculus/LinearSpline1D.cs
> +			}
nice, thanks!

2021-10-02 16:38 UTC, merged